openapi: 3.0.1
info:
  title: MELI CHALLENGE API
  description: This API Handle MELI Products.
  termsOfService: https://developers.mercadolibre.com.ar/es_ar/terminos-y-condiciones
  contact:
    name: API Support
    url: https://developers.mercadolibre.com.ar/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:8080/
- url: https://localhost:8080/
paths:
  /local/api/load-file:
    post:
      tags:
      - LoadFile
      summary: Load File by a request form and save it in the database SQLite
      description: Load File by a request form and save it in the database SQLite
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
              - file
              type: object
              properties:
                file:
                  type: string
                  description: File to be loaded
                  format: binary
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web.response'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web.errorResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/web.errorResponse'
components:
  schemas:
    web.errorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    web.response:
      type: object
      properties:
        data:
          type: object
x-original-swagger-version: "2.0"
